name: Test publish marketplace
description: Testing publishing
author: Jayatirth Kulkarni
branding:
  icon: 'thumbs-up'
  color: 'white'
runs:
  using: "composite"
  steps:     
    - name: Echo
      shell: bash
      run: |
        echo Heyyyyy
    - uses: JayatirthKulkarni/test-publish-repo/.github/workflows/actions.yml
    - uses: JayatirthKulkarni/test-publish-repo/.github/workflows/simple.yml